web/router.ex
defmodule RlTools.Router do
  use RlTools.Web, :router

  def put_empty_title(conn, _), do: conn |> assign(:title, nil)

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :put_empty_title
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", RlTools do
    pipe_through :browser # Use the default browser stack

    get "/", LeaderboardPageController, :index
    get "/about", AboutPageController, :about
    get "/leaderboard/:leaderboard_id", LeaderboardPageController, :leaderboard
    get "/player/:platform/:player_id", PlayerStatsPageController, :index

    get "/player/lookup", PlayerLookupPageController, :index
    post "/player/lookup", PlayerLookupPageController, :lookup
  end

  scope "/api", RlTools do
    pipe_through :api

    get "/player/:platform/:player_id/values/:leaderboards", PlayerValuesController, :player_values
  end

  # Other scopes may use custom stacks.
  # scope "/api", RlTools do
  #   pipe_through :api
  # end
end

web/controllers/leaderboard_page_controller.ex
defmodule RlTools.LeaderboardPageController do
  use RlTools.Web, :controller

  def leaderboard(conn, %{"leaderboard_id" => id}) do
    leaderboard = RlTools.Repo.one!(from(l in RlTools.Leaderboard,
        where: l.api_id == ^id))
    last_fetch = Repo.one!(from f in RlTools.FetchPass,
        where: not is_nil(f.end),
        order_by: [desc: f.time],
        limit: 1)

    leaderboard_values = Repo.all(from v in RlTools.LeaderboardValue,
        where: v.leaderboard_id == ^leaderboard.id
            and v.fetch_pass_id == ^last_fetch.id,
        order_by: [desc: v.value],
        limit: 100,
        preload: [:player])

    render conn, "leaderboard.html", %{
      leaderboard: leaderboard,
      leaderboard_values: leaderboard_values
    }
  end

  def index(conn, _params) do
    redirect conn, to: leaderboard_page_path RlTools.Endpoint, :leaderboard, "1v1"
  end
end

web/views/leaderboard_page_view.ex
defmodule RlTools.LeaderboardPageView do
  use RlTools.Web, :view
end

web/templates/leaderboard_page/index.html.eex
<div class="mdl-layout mdl-js-layout mdl-layout--fixed-drawer mdl-layout--fixed-header mdl-layout--fixed-tabs">

  <header class="mdl-layout__header id-casting-shadow">
    <div class="mdl-layout__header-row">
      <span class="mdl-layout-title">Rocket League Top</span>
      <div class="mdl-layout-spacer"></div>
    </div>
    <div class="mdl-layout__tab-bar mdl-js-ripple-effect">
      <%= for leaderboard <- @leaderboards do %>
        <a href="#leaderboard_<%= leaderboard.api_id %>" class="mdl-layout__tab <%= if leaderboard.id == 1, do: "is-active" %>"><%= leaderboard.name %></a>
      <% end %>
      <!--<a href="#fixed-tab-1" class="mdl-layout__tab is-active">Tab 1</a>
      <a href="#fixed-tab-2" class="mdl-layout__tab">Tab 2</a>
      <a href="#fixed-tab-3" class="mdl-layout__tab">Tab 3</a>-->
    </div>
  </header>

  <%= render RlTools.SharedView, "side_drawer.html", conn: @conn %>

  <main class="mdl-layout__content mdl-color--grey-100">
    <%= for {leaderboard, index} <- Enum.with_index(@leaderboards) do %>
      <section class="mdl-layout__tab-panel <%= if leaderboard.id == 1, do: "is-active" %>" id="leaderboard_<%= leaderboard.api_id %>">
        <div style="max-width: 600px;" class="mdl-grid">
          <table style="width: 100%;" class="mdl-data-table mdl-js-data-table mdl-shadow--2dp">
            <thead>
              <tr>
                <th>Rank</th>
                <th class="mdl-data-table__cell--non-numeric">Name</th>
                <th>Value</th>
              </tr>
            </thead>
            <tbody>
              <%= for {player, player_index} <- Enum.with_index(Enum.fetch!(@leaderboard_values, index)) do %>
                <tr>
                  <td><%= player_index + 1 %></td>
                  <td class="mdl-data-table__cell--non-numeric">
                    <a href="<%= player_stats_page_path @conn, :index, player.player.platform, player.player.player_id %>"><%= player.player.name %></a>
                  </td>
                  <td><%= player.value %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </section>
    <% end %>
  </main>
</div>

web/templates/leaderboard_page/leaderboard.html.eex
<div class="mdl-layout mdl-js-layout mdl-layout--fixed-drawer mdl-layout--fixed-header">

  <header class="mdl-layout__header id-casting-shadow">
    <div class="mdl-layout__header-row">
      <span class="mdl-layout-title">Rocket League Top</span>
      <div class="mdl-layout-spacer"></div>
    </div>
  </header>

  <%= render RlTools.SharedView, "side_drawer.html", conn: @conn, current: {:leaderboard, @leaderboard.id} %>

  <main class="mdl-layout__content mdl-color--grey-100">
    <div style="max-width: 600px;" class="mdl-grid">
      <table style="width: 100%;" class="mdl-data-table mdl-js-data-table mdl-shadow--2dp">
        <thead>
          <tr>
            <th>Rank</th>
            <th class="mdl-data-table__cell--non-numeric">Name</th>
            <th>Value</th>
          </tr>
        </thead>
        <tbody>
          <%= for {player, player_index} <- Enum.with_index(@leaderboard_values) do %>
            <tr>
              <td><%= player_index + 1 %></td>
              <td class="mdl-data-table__cell--non-numeric">
                <a href="<%= player_stats_page_path @conn, :index, player.player.platform, player.player.player_id %>"><%= player.player.name %></a>
              </td>
              <td><%= player.value %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </main>

</div>