web/router.ex
defmodule RlTools.Router do
  use RlTools.Web, :router

  def put_empty_title(conn, _), do: conn |> assign(:title, nil)

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :put_empty_title
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", RlTools do
    pipe_through :browser # Use the default browser stack

    get "/", LeaderboardPageController, :index
    get "/about", AboutPageController, :about
    get "/leaderboard/:leaderboard_id", LeaderboardPageController, :leaderboard
    get "/player/:platform/:player_id", PlayerStatsPageController, :index

    get "/player/lookup", PlayerLookupPageController, :index
    post "/player/lookup", PlayerLookupPageController, :lookup
  end

  scope "/api", RlTools do
    pipe_through :api

    get "/player/:platform/:player_id/values/:leaderboards", PlayerValuesController, :player_values
  end

  # Other scopes may use custom stacks.
  # scope "/api", RlTools do
  #   pipe_through :api
  # end
end

web/views/shared_view.ex
defmodule RlTools.SharedView do
  use RlTools.Web, :view

  def get_leaderboards do
    RlTools.Repo.all(RlTools.Leaderboard)
  end
end

web/templates/shared/side_drawer.html.eex
<% active = "navigation-active" %>
<% current = assigns[:current] %>

<div class="mdl-layout__drawer">

  <style>
    .navigation-divider {
      width: 100%;
      border-bottom: 1px #ddd solid; 
      margin: 8px 0px;
    }
    
    .navigation-active {
      background-color: #e0e0e0 !important;
    }
    .navigation-active:hover {
      background-color: #d0d0d0 !important;
    }

    .navigation-no-link:hover {
      background-color: #fafafa !important;
    }
  </style>

  <nav class="sidebar-navigation mdl-navigation">
    <a class="mdl-navigation__link navigation-no-link">
      <i class="material-icons" role="presentation">list</i>
      Leaderboards
    </a>
    <%= for leaderboard <- get_leaderboards do %>
      <a class="mdl-navigation__link 
        <%= if current == {:leaderboard, leaderboard.id}, do: active %>" 
         href="<%= leaderboard_page_path @conn, :leaderboard, leaderboard.api_id %>">
        <i class="material-icons" role="presentation">p</i>
        <%= leaderboard.name %>
      </a>
    <% end %>
    <div class="navigation-divider"></div>
    <a class="mdl-navigation__link <%= if current == :player_lookup, do: active %>" 
       href="<%= player_lookup_page_path @conn, :index %>">
      <i class="material-icons" role="presentation">person</i>
      Lookup Player
    </a>
    <a class="mdl-navigation__link" href="http://docs.rocketleaguetop.apiary.io/">
      <i class="material-icons" role="presentation">device_hub</i>
      API
    </a>
    <a class="mdl-navigation__link <%= if current == :about, do: active %>" 
       href="<%= about_page_path @conn, :about %>">
      <i class="material-icons" role="presentation">info</i>
      About
    </a>
    <div class="mdl-layout-spacer"></div>
  </nav>
</div>